branches: [ 'master' ]
repositoryUrl: 'git@github.com:holomekc/ioBroker.bshb.git'
tagFormat: ${version}
plugins:
  # https://github.com/semantic-release/semantic-release/blob/master/docs/extending/plugins-list.md
  - '@semantic-release/commit-analyzer'
  - './semantic-release/changelog'
  - './semantic-release/iobroker'
  - '@semantic-release/git'
  - '@semantic-release/exec'
  - '@semantic-release/github'
  - 'semantic-release-yarn'

dryRun: false
ci: true

analyzeCommits:
  # https://github.com/semantic-release/commit-analyzer
  - path: '@semantic-release/commit-analyzer'
    preset: 'conventionalcommits'
    # Default rules: https://github.com/semantic-release/commit-analyzer/blob/master/lib/default-release-rules.js
    releaseRules:
      - type: 'chore'
        scope: 'deps'
        release: 'patch'
      - type: 'chore'
        scope: 'release'
        release: false

verifyRelease:
  - path: '@semantic-release/exec'
    verifyReleaseCmd: |
      #!/bin/bash
      echo "version=${nextRelease.version}" >> "$GITHUB_OUTPUT" || echo "Most likely no ci env. Skipping export of ${nextRelease.version}"

prepare:
  - path: './semantic-release/changelog'
  - path: './semantic-release/iobroker'
  - path: 'semantic-release-yarn'
  - path: '@semantic-release/git'
    assets:
      - "README.md"
      - "CHANGELOG_OLD.md"
      - "package.json"
      - "yarn.lock"
      - "io-package.json"

success:
  - path: '@semantic-release/exec'
    successCmd: |
      #!/bin/bash
      ./release-tags.sh "${nextRelease.version}"

  - path: '@semantic-release/github'
    successComment: |
      :tada: This <%= issue.pull_request ? 'pull request' : 'issue' %> is included in version <%= '[' + nextRelease.version + '](https://github.com/holomekc/ioBroker.bshb/releases/tag/' + nextRelease.version + ')' %>

fail:
  - path: '@semantic-release/github'
    labels: false
    assignees:
      - '@holomekc'
