export const FUNCTIONS: { [FunctionName: string]: string } = {
    TemperatureLevel: 'heating',
    TemperatureOffset: 'heating',
    Thermostat: 'heating',
    ValveTappet: 'heating',
    RoomClimateControl: 'heating',
    TemperatureLevelConfiguration: 'heating',
    VentilationDelay: 'heating',
    IntrusionDetectionControl: 'security',
    SurveillanceAlarm: 'security',
    CommunicationQuality: 'communicationQuality',
    BatteryLevel: 'battery',
    AirQualityLevel: 'airQuality',
    SmokeSensitivity: 'smokeSensitivity',
    airPurityGuardian: 'airQuality',
};