name: 'Pull Request Labeler'
on:
  - pull_request

jobs:
  labeler:
    name: Label Pull requests
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          sync-labels: true
