name: Test

# Run this job on all pushes and pull requests
# as well as tags with a semantic version
on:
  push:
    branches:
      - "*"
  pull_request: { }

# Cancel previous PR/branch runs when a new commit is pushed
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 1

jobs:
  # Performs quick checks before the expensive test runs
  check-and-lint:
    if: contains(github.event.head_commit.message, '[skip ci]') == false

    runs-on: ubuntu-latest

    steps:
      - uses: ioBroker/testing-action-check@v1
        with:
          node-version: 22.x
          install-command: 'corepack enable && yarn install'
          lint-command: 'yarn run lint'
          test-command: 'yarn run test:package'
          type-checking: true
          lint: true

  # Runs adapter tests on all supported node versions and OSes
  adapter-tests:
    if: contains(github.event.head_commit.message, '[skip ci]') == false

    needs: [ check-and-lint ]

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [ 20.x, 22.x ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - uses: ioBroker/testing-action-adapter@v1
        with:
          node-version: ${{ matrix.node-version }}
          os: ${{ matrix.os }}
          install-command: 'corepack enable && yarn install'
          unit-test-command: 'yarn run test:unit'
          integration-test-command: 'yarn run test:integration'
          build-command: 'yarn run build'
          build: true
